# Generated by Django 5.1 on 2026-03-16 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('DEVOIR', 'Devoir a rendre'), ('EXERCICE', 'Exercice'), ('PROJET', 'Projet'), ('LECTURE', 'Lecture obligatoire')], default='DEVOIR', max_length=15)),
                ('description', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('date_limite', models.DateField()),
                ('note_sur', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('statut', models.CharField(choices=[('PUBLIE', 'Publie'), ('CLOS', 'Clos'), ('ARCHIVE', 'Archive')], default='PUBLIE', max_length=15)),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='devoirs/sujets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matiere_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='academic.matieresalle')),
                ('publie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoirs_publies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devoir',
                'ordering': ['-date_limite'],
            },
        ),
        migrations.CreateModel(
            name='SoumissionDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_texte', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='devoirs/soumissions/')),
                ('statut', models.CharField(choices=[('SOUMIS', 'Soumis'), ('CORRIGE', 'Corrige'), ('EN_RETARD', 'Soumis en retard')], default='SOUMIS', max_length=15)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commentaire_prof', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_correction', models.DateTimeField(blank=True, null=True)),
                ('corrige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_devoirs', to=settings.AUTH_USER_MODEL)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='devoirs.devoir')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_devoirs', to='students.eleve')),
            ],
            options={
                'ordering': ['-date_soumission'],
                'unique_together': {('devoir', 'eleve')},
            },
        ),
    ]
