# Generated by Django 6.0.2 on 2026-03-16 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_eleve', models.CharField(max_length=100)),
                ('prenom_eleve', models.CharField(max_length=100)),
                ('sexe_eleve', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('niveau_souhaite', models.CharField(max_length=50)),
                ('est_redoublant', models.BooleanField(default=False)),
                ('ancienne_ecole', models.CharField(blank=True, max_length=200)),
                ('nom_parent', models.CharField(max_length=100)),
                ('prenom_parent', models.CharField(blank=True, max_length=100)),
                ('telephone_parent', models.CharField(max_length=20)),
                ('telephone_wa_parent', models.CharField(blank=True, max_length=20)),
                ('email_parent', models.EmailField(blank=True, max_length=254)),
                ('profession_parent', models.CharField(blank=True, max_length=100)),
                ('adresse_parent', models.CharField(blank=True, max_length=200)),
                ('lien_parent', models.CharField(choices=[('PERE', 'Pere'), ('MERE', 'Mere'), ('TUTEUR', 'Tuteur legal'), ('AUTRE', 'Autre')], default='TUTEUR', max_length=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validee — compte cree'), ('REJETEE', 'Rejetee')], default='EN_ATTENTE', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('eleve_cree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preinscription', to='students.eleve')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preinscriptions_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pre-inscription',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
