# Generated by Django 5.1 on 2026-03-15 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('est_obligatoire', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('SALAIRE', 'Salaire'), ('FOURNITURE', 'Fourniture'), ('ENTRETIEN', 'Entretien'), ('EQUIPEMENT', 'Équipement'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FraisEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='students.eleve')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.typefrais')),
            ],
            options={
                'unique_together': {('eleve', 'type_frais', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moyen', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('numero_recu', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='students.eleve')),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='finance.fraiseleve')),
                ('recu_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('cible', models.CharField(choices=[('TOUS', 'Tous'), ('NIVEAU', 'Par niveau'), ('SALLE', 'Par salle')], default='TOUS', max_length=10)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.anneescolaire')),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.niveau')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.salleclasse')),
            ],
        ),
        migrations.CreateModel(
            name='TarifNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_inscription', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_scolarite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_examen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.anneescolaire')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.niveau')),
            ],
            options={
                'unique_together': {('niveau', 'annee')},
            },
        ),
    ]
