# Generated by Django 5.1 on 2026-03-15 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/eleves/')),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXCLU', 'Exclu'), ('TRANSFERE', 'Transféré')], default='INSCRIT', max_length=20)),
                ('redoublant', models.BooleanField(default=False)),
                ('contact_urgence', models.CharField(blank=True, max_length=100)),
                ('telephone_urgence', models.CharField(blank=True, max_length=20)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_eleve', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Élève',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('telephone2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('langue', models.CharField(choices=[('FR', 'Français'), ('EW', 'Ewe'), ('KA', 'Kabyè')], default='FR', max_length=5)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_parent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent/Tuteur',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFEREE', 'Transférée'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée')], default='ACTIVE', max_length=15)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('numero_ordre', models.IntegerField(blank=True, null=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academic.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='students.eleve')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academic.salleclasse')),
            ],
            options={
                'ordering': ['salle__nom', 'eleve__nom'],
                'unique_together': {('eleve', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='EleveParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur légal'), ('AUTRE', 'Autre')], default='TUTEUR', max_length=10)),
                ('est_contact_principal', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='students.eleve')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='students.parent')),
            ],
            options={
                'unique_together': {('eleve', 'parent')},
            },
        ),
    ]
