# Generated by Django 5.1 on 2026-03-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='GESTo', max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('type_ecole', models.CharField(choices=[('PRIVE', 'Établissement privé'), ('PUBLIC', 'Établissement public')], default='PRIVE', max_length=10)),
                ('systeme_defaut', models.CharField(choices=[('TRIMESTRIEL', 'Trimestriel (T1/T2/T3)'), ('SEMESTRIEL', 'Semestriel (S1/S2)')], default='TRIMESTRIEL', max_length=15)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('ministre_tutelle', models.CharField(blank=True, max_length=200)),
                ('devise', models.CharField(blank=True, default='Travail – Liberté – Patrie', max_length=100)),
                ('heure_rapport_directeur', models.TimeField(default='09:00')),
                ('heure_rapport_censeur', models.TimeField(default='18:00')),
                ('seuil_retards_consecutifs', models.IntegerField(default=5)),
                ('seuil_retards_periode', models.IntegerField(default=10)),
                ('seuil_jours_periode', models.IntegerField(default=20)),
                ('seuil_alerte_dette_jours', models.IntegerField(default=30)),
                ('wa_numero_source', models.CharField(blank=True, max_length=20)),
                ('wa_numero_secours', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration école',
            },
        ),
        migrations.CreateModel(
            name='SauvegardeAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.CharField(max_length=300)),
                ('taille_ko', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('OK', 'Succès'), ('ERREUR', 'Erreur')], default='OK', max_length=10)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
