# Generated by Django 6.0.2 on 2026-03-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sauvegardeauto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sauvegarde'},
        ),
        migrations.RemoveField(
            model_name='sauvegardeauto',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='sauvegardeauto',
            name='message',
        ),
        migrations.RemoveField(
            model_name='sauvegardeauto',
            name='taille_ko',
        ),
        migrations.AddField(
            model_name='sauvegardeauto',
            name='fichier_db',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sauvegardeauto',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sauvegardeauto',
            name='taille_mb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sauvegardeauto',
            name='type',
            field=models.CharField(choices=[('AUTOMATIQUE', 'Automatique'), ('MANUELLE', 'Manuelle')], default='AUTOMATIQUE', max_length=15),
        ),
        migrations.AlterField(
            model_name='sauvegardeauto',
            name='statut',
            field=models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('EN_COURS', 'En cours')], default='EN_COURS', max_length=15),
        ),
    ]
