# Generated by Django 5.1 on 2026-03-15 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ecole', models.CharField(default='GESTo', max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='documents/logos/')),
                ('signature_directeur', models.ImageField(blank=True, null=True, upload_to='documents/signatures/')),
                ('cachet', models.ImageField(blank=True, null=True, upload_to='documents/cachets/')),
                ('pied_page', models.CharField(blank=True, max_length=300)),
                ('ministre_tutelle', models.CharField(blank=True, max_length=200)),
                ('devise_nationale', models.CharField(blank=True, default='Travail – Liberté – Patrie', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration document',
            },
        ),
        migrations.CreateModel(
            name='CertificatScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('date_delivrance', models.DateField(auto_now_add=True)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.anneescolaire')),
                ('delivre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='students.eleve')),
            ],
            options={
                'ordering': ['-date_delivrance'],
            },
        ),
    ]
