# Generated by Django 5.1 on 2026-03-15 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'ordering': ['-nom'],
            },
        ),
        migrations.CreateModel(
            name='CreneauType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('type', models.CharField(choices=[('COURS', 'Cours'), ('PAUSE', 'Pause'), ('RECREATION', 'Récréation')], default='COURS', max_length=15)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('jours_applicables', models.CharField(default='LUNDI,MARDI,MERCREDI,JEUDI,VENDREDI', max_length=100)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10)),
                ('est_libre', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé et publié')], default='BROUILLON', max_length=15)),
                ('contrainte_violee', models.BooleanField(default=False)),
                ('note_contrainte', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Emploi du temps',
            },
        ),
        migrations.CreateModel(
            name='GroupeMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SCIENTIFIQUE', 'Scientifiques'), ('LITTERAIRE', 'Littéraires'), ('FACULTATIF', 'Facultatives'), ('AUTRE', 'Autre')], default='AUTRE', max_length=15)),
                ('ordre', models.IntegerField(default=0)),
                ('est_obligatoire', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Matière',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MatiereSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('heures_semaine', models.DecimalField(decimal_places=1, default=2, max_digits=4)),
                ('est_facultative', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['groupe__ordre', '-coefficient', 'matiere__nom'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('ordre', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('systeme', models.CharField(choices=[('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel')], default='TRIMESTRIEL', max_length=15)),
                ('type_ecole', models.CharField(choices=[('PRIVE', 'Privé'), ('PUBLIC', 'Public')], default='PRIVE', max_length=10)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='NiveauHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre')], default='TRIMESTRE', max_length=10)),
                ('numero', models.IntegerField()),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SalleClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField(default=40)),
                ('batiment', models.CharField(blank=True, max_length=50)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salle de classe',
                'verbose_name_plural': 'Salles de classe',
                'ordering': ['niveau__ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.anneescolaire')),
            ],
            options={
                'ordering': ['jour', 'heure_debut'],
            },
        ),
    ]
