# Generated by Django 5.1 on 2026-03-15 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibiliteprof',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.anneescolaire'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='creneau_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.creneautype'),
        ),
        migrations.AddField(
            model_name='matieresalle',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.groupematiere'),
        ),
        migrations.AddField(
            model_name='matieresalle',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.matiere'),
        ),
        migrations.AddField(
            model_name='matieresalle',
            name='professeur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROFESSEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_enseignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='matiere_salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.matieresalle'),
        ),
        migrations.AddField(
            model_name='groupematiere',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_matieres', to='academic.niveau'),
        ),
        migrations.AddField(
            model_name='niveauhoraire',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.anneescolaire'),
        ),
        migrations.AddField(
            model_name='niveauhoraire',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_horaires', to='academic.niveau'),
        ),
        migrations.AddField(
            model_name='creneautype',
            name='niveau_horaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='academic.niveauhoraire'),
        ),
        migrations.AddField(
            model_name='periode',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='academic.anneescolaire'),
        ),
        migrations.AddField(
            model_name='salleclasse',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='academic.anneescolaire'),
        ),
        migrations.AddField(
            model_name='salleclasse',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='academic.niveau'),
        ),
        migrations.AddField(
            model_name='salleclasse',
            name='titulaire',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROFESSEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salles_titulaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matieresalle',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='academic.salleclasse'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='academic.salleclasse'),
        ),
        migrations.AlterUniqueTogether(
            name='groupematiere',
            unique_together={('niveau', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='niveauhoraire',
            unique_together={('niveau', 'annee')},
        ),
        migrations.AlterUniqueTogether(
            name='creneautype',
            unique_together={('niveau_horaire', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='periode',
            unique_together={('annee', 'type', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='salleclasse',
            unique_together={('niveau', 'annee', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='matieresalle',
            unique_together={('salle', 'matiere')},
        ),
        migrations.AlterUniqueTogether(
            name='emploidutemps',
            unique_together={('salle', 'creneau_type', 'jour', 'annee')},
        ),
    ]
