# Generated by Django 5.1 on 2026-03-15 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('DEVOIR', 'Devoir'), ('COMPOSITION', 'Composition'), ('INTERROGATION', 'Interrogation'), ('TP', 'TP')], default='DEVOIR', max_length=20)),
                ('date', models.DateField()),
                ('note_sur', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée — prête pour saisie'), ('EN_SAISIE', 'En cours de saisie'), ('NOTES_SAISIES', 'Notes saisies — validation en attente'), ('VALIDEE_FINALE', 'Validée définitivement'), ('REJETEE', 'Rejetée')], default='BROUILLON', max_length=20)),
                ('commentaire_rejet', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_creees', to=settings.AUTH_USER_MODEL)),
                ('matiere_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.matieresalle')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.periode')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évaluation',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AutorisationSaisie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_autorisee', models.BooleanField(default=True)),
                ('notes_saisies', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autorise_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorisations_donnees', to=settings.AUTH_USER_MODEL)),
                ('saisie_par', models.ForeignKey(blank=True, help_text='Null = professeur de la matière', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorisations_recues', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autorisation', to='grades.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('BLANC', 'Examen Blanc'), ('OFFICIEL', 'Examen Officiel'), ('BILAN', 'Bilan de fin de période')], default='BLANC', max_length=20)),
                ('cible', models.CharField(choices=[('NIVEAU', 'Tout le niveau'), ('SALLE', 'Salle spécifique')], default='NIVEAU', max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PREPARATION', 'En préparation'), ('EN_COURS', 'En cours'), ('NOTES_EN_SAISIE', 'Notes en saisie'), ('NOTES_SAISIES', 'Notes saisies — validation en attente'), ('VALIDE', 'Validé')], default='PREPARATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_crees', to=settings.AUTH_USER_MODEL)),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='academic.niveau')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='academic.periode')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='academic.salleclasse')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamenMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('note_sur', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('notes_saisies', models.BooleanField(default=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='grades.examen')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.matiere')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examen_matieres_a_saisir', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('examen', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('est_absent', models.BooleanField(default=False)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('est_validee', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.eleve')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='grades.evaluation')),
                ('saisie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evaluation', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nouvelle_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('raison', models.CharField(blank=True, max_length=200)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='grades.note')),
            ],
            options={
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='MoyenneGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('effectif_classe', models.IntegerField(default=0)),
                ('moy_la_plus_forte', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('moy_la_plus_faible', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('moy_de_la_classe', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mention_travail', models.CharField(blank=True, max_length=50)),
                ('tableau_honneur', models.BooleanField(default=False)),
                ('assiduite', models.CharField(blank=True, max_length=50)),
                ('conduite', models.CharField(blank=True, max_length=50)),
                ('nb_absences', models.IntegerField(default=0)),
                ('nb_retards', models.IntegerField(default=0)),
                ('decision', models.CharField(choices=[('ADMIS', 'Admis(e)'), ('EN_ATTENTE', 'En attente'), ('REDOUBLEMENT', 'Redoublement'), ('EXCLU', 'Exclu(e)')], default='EN_ATTENTE', max_length=15)),
                ('decision_texte', models.CharField(blank=True, max_length=200)),
                ('appreciation_conseil', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.eleve')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.periode')),
            ],
            options={
                'unique_together': {('eleve', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='MoyenneMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_classe', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('note_composition', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moyenne_eleve', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('appreciation', models.CharField(blank=True, max_length=50)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.eleve')),
                ('matiere_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.matieresalle')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.periode')),
            ],
            options={
                'unique_together': {('eleve', 'matiere_salle', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='NoteComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('est_absent', models.BooleanField(default=False)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.eleve')),
                ('matiere_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_compo', to='academic.matieresalle')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.periode')),
                ('saisie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('matiere_salle', 'periode', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='NoteExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('est_absent', models.BooleanField(default=False)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.eleve')),
                ('examen_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='grades.examenmatiere')),
                ('saisie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('examen_matiere', 'eleve')},
            },
        ),
    ]
