# Generated by Django 6.0.2 on 2026-03-16 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        ('communication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('FERIE', 'Jour ferie'), ('VACANCES', 'Vacances'), ('EXAMEN', 'Examen'), ('REUNION', 'Reunion'), ('EVENEMENT', 'Evenement scolaire'), ('AUTRE', 'Autre')], default='EVENEMENT', max_length=15)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('concerne_tous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='academic.anneescolaire')),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evenement calendrier',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ReunionParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('lieu', models.CharField(default='Salle de conference', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiee'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminee'), ('ANNULEE', 'Annulee')], default='PLANIFIEE', max_length=15)),
                ('nb_convocations_envoyees', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.anneescolaire')),
                ('organisee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_organisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reunion parents',
                'ordering': ['-date'],
            },
        ),
    ]
