# Generated by Django 5.1 on 2026-03-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'En retard'), ('ABSENT_JUSTIFIE', 'Absent justifié'), ('RETARD_JUSTIFIE', 'Retard justifié')], default='PRESENT', max_length=20)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('est_justifiee', models.BooleanField(default=False)),
                ('date_pointage', models.DateTimeField(auto_now_add=True)),
                ('modifie_par_surveillant', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['eleve__nom'],
            },
        ),
        migrations.CreateModel(
            name='SeancePointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jour', models.CharField(blank=True, max_length=10)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SOUMIS', 'Soumis'), ('VERROUILLE', 'Verrouillé — 10min dépassées')], default='EN_COURS', max_length=15)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_verrou', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
