# Generated by Django 5.1 on 2026-03-15 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('attendance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='students.eleve'),
        ),
        migrations.AddField(
            model_name='presence',
            name='pointe_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seancepointage',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.creneautype'),
        ),
        migrations.AddField(
            model_name='seancepointage',
            name='matiere_salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_pointage', to='academic.matieresalle'),
        ),
        migrations.AddField(
            model_name='seancepointage',
            name='soumis_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_soumises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presence',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='attendance.seancepointage'),
        ),
        migrations.AlterUniqueTogether(
            name='seancepointage',
            unique_together={('matiere_salle', 'date', 'creneau')},
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('eleve', 'seance')},
        ),
    ]
